package io.github.sufarook.kiln.sample.compose

import app.cash.sqldelight.db.SqlDriver
import kotlinx.coroutines.flow.Flow

/**
 * All persistence for the sample. Every repository here is generated — the only
 * hand-written database code in this file is `createTable()` and the calls below.
 */
class TaskStore(driver: SqlDriver) {

    private val tasks = TaskRepository(driver)
    private val tags = TagRepository(driver)
    private val taskTags = TaskTagRepository(driver)

    init {
        // Safe on every launch: creates the table if missing, and auto-migrates
        // the schema if the data class changed since last run.
        tasks.createTable()
        tags.createTable()
        taskTags.createTable()
    }

    // ── Reactive reads — re-emit after every write to that table ──────────────

    fun observeTasks(): Flow<List<Task>> = tasks.observeAll()

    fun observeTags(): Flow<List<Tag>> = tags.observeAll()

    fun observeTaskTags(): Flow<List<TaskTag>> = taskTags.observeAll()

    // ── Tasks ─────────────────────────────────────────────────────────────────

    suspend fun addTask(title: String) = tasks.insert(Task(title = title))

    suspend fun toggleDone(task: Task) = tasks.update(task.copy(isDone = !task.isDone))

    /**
     * Kiln doesn't enable SQLite foreign-key enforcement, so the join rows are
     * removed explicitly. `deleteByTask` is generated from `@Relation` on
     * TaskTag.taskId — that's the whole cascade, one call.
     */
    suspend fun deleteTask(task: Task) {
        taskTags.deleteByTask(task.id)
        tasks.delete(task.id)
    }

    // ── Tags & assignment (the junction table in action) ──────────────────────

    suspend fun addTag(name: String) = tags.insert(Tag(name = name))

    suspend fun assign(taskId: Long, tagId: Long) = taskTags.insert(TaskTag(taskId, tagId))

    /** Deleting by the generated composite key type. */
    suspend fun unassign(taskId: Long, tagId: Long) = taskTags.delete(TaskTagKey(taskId, tagId))

    /** Every tag currently attached to a task — generated by `@Relation`. */
    suspend fun tagIdsFor(taskId: Long): List<Long> =
        taskTags.findByTask(taskId).map { it.tagId }

    /** Seeds a few tags the first time the app runs. */
    suspend fun seedTagsIfEmpty() {
        if (tags.count() == 0L) {
            listOf("home", "work", "urgent").forEach { addTag(it) }
        }
    }
}
