package io.github.sufarook.kiln.sample

import android.app.Application
import io.github.sufarook.kiln.runtime.AndroidDatabaseDriverFactory

class SampleApplication : Application() {

    // Generated by Kiln — available app-wide
    lateinit var todoRepo: TodoRepository
        private set

    override fun onCreate() {
        super.onCreate()
        val driver = AndroidDatabaseDriverFactory(this).create("todos.db")
        todoRepo = TodoRepository(driver)
        todoRepo.createTable() // safe to call repeatedly — uses IF NOT EXISTS
    }
}
